# Generated by Django 4.0.4 on 2022-05-24 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_timestamp_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 8, 8, 46, 883197, tzinfo=utc)),
        ),
    ]
